import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#363940",
        tertiary: "#f5d0ff",
        "on-tertiary": "#520071",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#5700c9",
        "primary-fixed-dim": "#4cd6ff",
        "secondary-fixed": "#e9ddff",
        "surface-variant": "#32353c",
        "on-tertiary-fixed-variant": "#74009f",
        "tertiary-fixed": "#f8d8ff",
        "inverse-primary": "#00677f",
        "secondary-container": "#7000ff",
        "inverse-on-surface": "#2e3037",
        "on-primary-fixed-variant": "#004e60",
        "tertiary-container": "#e9a9ff",
        "on-surface-variant": "#bbc9cf",
        background: "#10131a",
        "on-primary-container": "#00566a",
        "on-background": "#e1e2eb",
        "tertiary-fixed-dim": "#ecb2ff",
        "on-primary": "#003543",
        "surface-dim": "#10131a",
        "on-surface": "#e1e2eb",
        "surface-container-low": "#191c22",
        "on-primary-fixed": "#001f28",
        error: "#ffb4ab",
        "surface-tint": "#4cd6ff",
        outline: "#859399",
        "inverse-surface": "#e1e2eb",
        "secondary-fixed-dim": "#d1bcff",
        "on-secondary-fixed": "#23005b",
        "on-error": "#690005",
        "on-tertiary-container": "#8000ae",
        surface: "#10131a",
        "error-container": "#93000a",
        "on-secondary": "#3c0090",
        "primary-container": "#00d1ff",
        "outline-variant": "#3c494e",
        "surface-container-high": "#272a31",
        "surface-container-highest": "#32353c",
        "on-secondary-container": "#ddcdff",
        "surface-container": "#1d2026",
        "on-tertiary-fixed": "#320047",
        primary: "#a4e6ff",
        secondary: "#d1bcff",
        "primary-fixed": "#b7eaff",
        "surface-container-lowest": "#0b0e14",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      boxShadow: {
        "cyan-glow": "0px 20px 40px rgba(0, 209, 255, 0.08)",
        "cyan-glow-lg": "0 0 20px rgba(164, 230, 255, 0.4)",
        "neon-primary": "0 0 15px rgba(164, 230, 255, 0.5)",
        "neon-secondary": "0 0 15px rgba(209, 188, 255, 0.5)",
        "node-current": "0 0 15px rgba(76, 214, 255, 0.8)",
      },
      animation: {
        "ping-slow": "ping 2s cubic-bezier(0, 0, 0.2, 1) infinite",
        flicker: "flicker 4s ease-in-out infinite",
        "draw-in": "drawIn 1.5s ease-out forwards",
        "float-up": "floatUp 0.6s ease-out forwards",
        "gradient-shift": "gradientShift 3s ease infinite",
      },
      keyframes: {
        flicker: {
          "0%, 100%": { opacity: "0.3" },
          "50%": { opacity: "0.8" },
        },
        floatUp: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        gradientShift: {
          "0%, 100%": { backgroundPosition: "0% 50%" },
          "50%": { backgroundPosition: "100% 50%" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
